{
 "title": "Temperature Dashboard",
 "tags": [
  "IoT",
  "Temperature"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time_sec,\n  value as value,\n  'temperature' as metric\nFROM DATA\nORDER BY timestamp ASC\n"
    }
   ]
  },
  {
   "title": "Average",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(value)\nFROM DATA\n"
    }
   ]
  },
  {
   "title": "Calculated Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  (max(timestamp) - min(timestamp))/60\nFROM DATA"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  ((max(timestamp) - min(timestamp))/60 - count(*))\nFROM DATA"
    }
   ]
  },
  {
   "title": "BROKER STATUS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  ISACTIVE\nFROM BROKER_STATUS"
    }
   ]
  },
  {
   "title": "LAST ACTIVE",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  TIMESTAMP*1000\nFROM BROKER_STATUS\nWHERE ISACTIVE\nORDER BY timestamp DESC"
    }
   ]
  },
  {
   "title": "Last Receive",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time_sec,\n  value as value,\n  'temperature' as metric\nFROM DATA\nORDER BY timestamp ASC\n"
    }
   ]
  },
  {
   "title": "Actual Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "rawSql": "SELECT\n  count(*)\nFROM DATA" }
   ]
  },
  {
   "title": "Missing Message",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  100*(((max(timestamp) - min(timestamp))/60 - count(*))/((max(timestamp) - min(timestamp))/60))\nFROM DATA"
    }
   ]
  },
  {
   "title": "DEVICE STATUS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  PINGTIME/1000 < 10 as ISACTIVE\nFROM DEVICE_STATUS\nORDER BY TIMESTAMP DESC"
    }
   ]
  },
  {
   "title": "LAST ACTIVE",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "format": "dateTimeAsIso",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  TIMESTAMP*1000\nFROM DEVICE_STATUS\nWHERE PINGTIME/1000 < 10\nORDER BY timestamp DESC"
    }
   ]
  },
  {
   "title": "Temperature History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "°C" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TIMESTAMP AS \"time\",\n  VALUE\nFROM DATA\nORDER BY TIMESTAMP"
    }
   ]
  },
  {
   "title": "DEVICE STATUS HISTORY",
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TIMESTAMP AS \"time\",\n  PINGTIME/1000\nFROM DEVICE_STATUS\nORDER BY TIMESTAMP"
    }
   ]
  },
  {
   "title": "BROKER STATUS HISTORY",
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  TIMESTAMP AS \"time\",\n  ISACTIVE\nFROM BROKER_STATUS\nWHERE\n  $__unixEpochFilter(TIMESTAMP)\nORDER BY TIMESTAMP"
    }
   ]
  }
 ]
}