{
 "title": "CO MONITORING",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "CO VALUE",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  TIME as time_sec,\n  RAW_VALUE as value,\n DEVICE_ID as metric\nFROM CO_DATA\nWHERE $__unixEpochFilter(TIME)\nORDER BY TIME ASC\n"
    }
   ]
  },
  {
   "title": "AVG CO VALUE",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  TIME as time_sec,\n  RAW_VALUE as value,\n DEVICE_ID as metric\nFROM CO_DATA\nWHERE $__unixEpochFilter(TIME)\nORDER BY TIME ASC\n"
    }
   ]
  },
  {
   "title": "CATEGORY",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "rawSql": "SELECT\n  TIME as time_sec,\n  VALUE as value,\n DEVICE_ID as metric\nFROM CO_DATA\nWHERE $__unixEpochFilter(TIME)\nORDER BY TIME ASC\n"
    }
   ]
  },
  {
   "title": "DAILY ISPU HISTORY",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  TIME as time_sec,\n  VALUE as value,\n  DEVICE_ID as metric\nFROM CO_DATA\nWHERE $__unixEpochFilter(TIME)\nORDER BY TIME ASC\n"
    }
   ]
  },
  {
   "title": "ISPU INDEX",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  TIME as time_sec,\n  VALUE as value,\n DEVICE_ID as metric\nFROM CO_DATA\nWHERE $__unixEpochFilter(TIME)\nORDER BY TIME ASC\n"
    }
   ]
  },
  {
   "title": "LAST RECEIVE",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT\n  TIME as time_sec,\n  VALUE as value,\n DEVICE_ID as metric\nFROM CO_DATA\nWHERE $__unixEpochFilter(TIME)\nORDER BY TIME ASC\n"
    }
   ]
  },
  {
   "title": "MESSAGE COUNT",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM CO_DATA\n"
    }
   ]
  },
  {
   "title": "MAP",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\r\n  TIME as time_sec,\r\n  VALUE as metric,\r\n  LATITUDE as latitude,\r\n  LONGITUDE as longitude,\r\n  CONCAT(\"Device \", DEVICE_ID, \" \") as name\r\nFROM CO_DATA\r\nORDER BY TIME DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "HISTORICAL CO FOR LAST 12 HOUR",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "conμgm3" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TIME as time_sec,\n  RAW_VALUE as value,\n DEVICE_ID as metric\nFROM CO_DATA\nWHERE $__unixEpochFilter(TIME)\nORDER BY TIME ASC\n"
    },
    {
     "rawSql": "  SELECT \r\n  \tCONCAT(CO_NEXT.DEVICE_ID, \" AVG\") AS 'metric', \r\n  \tFROM_UNIXTIME(CO_NEXT.TIME - 450) AS 'time_sec', \r\n  \tAVG(CO.RAW_VALUE) AS MinAvg\r\n  FROM CO_DATA CO\r\n  JOIN CO_DATA CO_NEXT \r\n    ON CO.DEVICE_ID = CO_NEXT.DEVICE_ID \r\n      AND TIMESTAMPDIFF(MINUTE, FROM_UNIXTIME(CO.TIME), FROM_UNIXTIME(CO_NEXT.TIME)) BETWEEN 0 AND 14\r\n  GROUP BY CO_NEXT.DEVICE_ID, FROM_UNIXTIME(CO_NEXT.TIME - 450)"
    }
   ]
  }
 ]
}