{
 "title": "ENVIRONMENT",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "\nSELECT\n  CASE \n    WHEN value <= 24 THEN \"DINGIN BANGET\"\n    WHEN value > 24 AND value <= 27 THEN \"DINGIN\"\n    WHEN value > 27 AND value <= 30 THEN \"HANGAT\"\n    WHEN value > 30 AND value <= 33 THEN \"PANAS\"\n    ELSE \"PANAS BANGET\"\n  END\nFROM ENVIRONMENT\nWHERE type = \"Temperature\"\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Dust",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "\nSELECT\n  CASE \n    WHEN value <= 12 THEN \"BAIK\"\n    WHEN value > 12 AND value <= 35 THEN \"SEDANG\"\n    WHEN value > 35 AND value <= 56 THEN \"TIDAK SEHAT\"\n    WHEN value > 56 THEN \"SANGAT TIDAK SEHAT\"\n  END\nFROM ENVIRONMENT\nWHERE type = \"Dust\"\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "\nSELECT\n  CASE \n    WHEN value <= 45 THEN \"KERING\"\n    WHEN value > 45 AND value <= 65 THEN \"IDEAL\"\n    WHEN value > 65 THEN \"LEMBAB\"\n  END\nFROM ENVIRONMENT\nWHERE type = \"Humidity\"\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Last Receive",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  timestamp\nFROM ENVIRONMENT\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value\nFROM ENVIRONMENT\nWHERE\n  type = \"Temperature\"\nORDER BY timestamp DESC"
    }
   ]
  },
  {
   "title": "Dust PM2.5 (ug)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value\nFROM ENVIRONMENT\nWHERE\n  type = \"Dust\"\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value\nFROM ENVIRONMENT\nWHERE\n  type = \"Humidity\"\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Historical Data",
   "type": "graph",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  type AS metric,\n  value\nFROM ENVIRONMENT\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value\nFROM ENVIRONMENT\nWHERE\n  type = \"Temperature\"\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Average Dust PM2.5 (ug)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value\nFROM ENVIRONMENT\nWHERE\n  type = \"Dust\"\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Average Humidity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value\nFROM ENVIRONMENT\nWHERE\n  type = \"Humidity\"\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Total Dust Data",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM ENVIRONMENT\nWHERE type = \"Dust\""
    }
   ]
  },
  {
   "title": "Total Temperature Data",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM ENVIRONMENT\nWHERE type = \"Temperature\""
    }
   ]
  },
  {
   "title": "Total Humidity Data",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM ENVIRONMENT\nWHERE type = \"Humidity\""
    }
   ]
  }
 ]
}